Added hips for leg rotation.
moraell/KinectMocap4Blender pull request #16
Opened 2020-04-03 15:00 UTC by LandryLT

Thank you so much for this wonderfull script. Just added reference to hips so the legs can rotate.

2020-04-03 20:03 UTC, moraell commented
Hi, thanks. Have you tested it ? Do you really have hip rotation with this? I remember not adding these bones because, as I remember it, they seemed to always have the same rotation as the lower spine bone. But maybe I missed something, here.

2020-04-03 20:44 UTC, LandryLT commented
Doesn't change that much, but if you don't put the hips, legs stay completely blocked on X-axis. With the modification you get around 90° Z rotation on the hips (after that, hips flip 180°)

2020-04-03 20:48 UTC, LandryLT commented
Bon confinement au passage ;)

2020-04-04 07:46 UTC, moraell commented
Merci, de même ;)
Je peux peut-être continuer en français?
D'un point de vue anatomique, cette solution est un peu caduque parce qu'en fait, les deux os ajoutés s'ajoutent à la base de la colonne pour former le bassin qui est d'un seul tenant. Mais cela permet de simuler la rotation qui manquait.
Donc effectivement, ça fonctionne. Toutefois, les vecteurs de référence sont erronés. En effet, il s'agit des directions de base de ces os pour l'armature kinect, qui sont parfaitement horizontaux. On devrait donc avoir Vector(1,0,0) et Vector (-1,0,0). J'ai testé avec une armature du plugin rigidbody dont j'ai modifié le "parenting" pour simuler les os désirés et ça marchait très mal avec les vecteurs précédents. C'est mieux avec les derniers.
J'espère trouver un jour le temps et l'énergie de refondre le système en utilisant les rotations données par le capteur car ça éviterait ces soucis, mais les multiples problèmes de changement de repère avec des quaternions et des référentiels différents me refroidissent un peu. 

Merci beaucoup pour ces modifs. Je me sens un peu idiote de ne pas y avoir pensé.

2020-04-04 07:48 UTC, moraell requested changes
Thanks, seems good. However, the (1,0,0.5) and (-1,0,0.5) vectors should be changed to (1,0,0) and (-1,0,0)

2020-04-04 12:14 UTC, LandryLT commented
Pour le coup je n'utilise pas une armature rigidbody mais une qui est générée à partir des données brutes des positions des jointures que la Kinect fournies (cf photo). J'ai complétement retiré les vecteurs références pour mon projet, ça marche plutôt bien. 

![image](https://user-images.githubusercontent.com/59315119/78450343-37a8fd00-767e-11ea-9ac5-ae624db6e6af.png)

2020-04-05 07:52 UTC, merged